name: 'Kickstart CDF Validation'
description: 'Validate CDF pattern integrity, file signatures, and prevent unauthorized Terraform files'

inputs:
  cdf_path:
    description: 'Path to CDF pattern directory (auto-detected if not specified)'
    required: false
    default: ''
  validation_level:
    description: 'Validation level: basic, full, or strict'
    required: false
    default: 'full'
  fail_on_unauthorized_tf:
    description: 'Fail if unauthorized Terraform files are found'
    required: false
    default: 'true'
  skip_signature_validation:
    description: 'Skip signature validation (for testing only)'
    required: false
    default: 'false'
  certificate_identity_regex:
    description: 'Regex to match certificate subject/identity when verifying'
    required: false
    default: '.*'
  certificate_issuer_regex:
    description: 'Regex to match certificate OIDC issuer when verifying'
    required: false
    default: '.*'
  insecure_ignore_tlog:
    description: 'Ignore transparency log when verifying signatures'
    required: false
    default: 'true'
  public_key:
    description: 'PEM public key to verify non-certificate signatures (optional)'
    required: false
    default: ''

outputs:
  validation_status:
    description: 'Validation result: passed, failed, or skipped'
    value: ${{ steps.run-validate.outputs.validation_status }}
  error_count:
    description: 'Number of validation errors found'
    value: ${{ steps.run-validate.outputs.error_count }}
  file_count:
    description: 'Number of files validated'
    value: ${{ steps.run-validate.outputs.file_count }}

runs:
  using: 'composite'
  steps:
    - name: Ensure cosign available (no sudo)
      shell: bash
      run: |
        if ! command -v cosign >/dev/null 2>&1; then
          echo "cosign not found; installing locally..."
          mkdir -p "$RUNNER_TEMP/bin"
          curl -sSL -o "$RUNNER_TEMP/bin/cosign" "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64"
          chmod +x "$RUNNER_TEMP/bin/cosign"
          echo "$RUNNER_TEMP/bin" >> "$GITHUB_PATH"
          # also export for current step and subsequent ones
          export PATH="$RUNNER_TEMP/bin:$PATH"
          echo "PATH=$RUNNER_TEMP/bin:$PATH" >> "$GITHUB_ENV"
        fi

    - name: Cosign version (diagnostic)
      shell: bash
      run: |
        echo "PATH=$PATH"
        command -v cosign || true
        cosign version || true

    - name: Run validation
      id: run-validate
      shell: bash
      run: |
        python3 "${{ github.action_path }}/scripts/validate.py" \
          --cdf-path "${{ inputs.cdf_path }}" \
          --validation-level "${{ inputs.validation_level }}" \
          --fail-on-unauthorized-tf "${{ inputs.fail_on_unauthorized_tf }}" \
          --skip-signature-validation "${{ inputs.skip_signature_validation }}" \
          --cert-identity-regex "${{ inputs.certificate_identity_regex }}" \
          --cert-issuer-regex "${{ inputs.certificate_issuer_regex }}" \
          --insecure-ignore-tlog "${{ inputs.insecure_ignore_tlog }}" \
          --public-key "${{ inputs.public_key }}"